import { type NextPage } from "next";
import Head from "next/head";
import { signOut } from "firebase/auth";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase";

const Home: NextPage = () => {
  const router = useRouter();
  const [user] = useAuthState(auth);

  useEffect(() => {
    if (!user) {
      router.push("/login");
    }
  });

  const handleLogout = async () => {
    await signOut(auth);
  };

  return (
    <>
      <Head>
        <title>5 Year Old</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="mx-4" onClick={handleLogout}>
          Logout
        </button>
      </main>
    </>
  );
};

export default Home;
