import { type NextPage } from "next";
import Head from "next/head";
import { signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Login: NextPage = () => {
  const provider = new GoogleAuthProvider();
  const [user] = useAuthState(auth);

  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push("/");
    }
  });

  const handleLogin = async () => {
    try {
      const result = await signInWithPopup(auth, provider);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Login | 5 Year Old</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-full flex-col items-center justify-center bg-gradient-to-b from-violet-500 to-violet-800 pb-64">
        <h1 className="mb-10 text-5xl font-bold text-white">
          Explain to me like I&apos;m 5 years old.
        </h1>
        <button
          className="rounded-full bg-black px-8 py-4 text-xl text-white"
          onClick={handleLogin}
        >
          Login
        </button>
      </div>
    </>
  );
};

export default Login;
