import { type NextPage } from "next";
import Head from "next/head";
import { signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Login: NextPage = () => {
  const provider = new GoogleAuthProvider();
  const [user] = useAuthState(auth);

  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push("/");
    }
  });

  const handleLogin = async () => {
    try {
      const result = await signInWithPopup(auth, provider);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>5 Year Old</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button className="mx-4" onClick={handleLogin}>
            Login
          </button>
        </div>
      </main>
    </>
  );
};

export default Login;
